# Generated by Django 5.1.3 on 2024-11-14 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispotify', '0001_Init_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-author', '-date']},
        ),
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='author',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(to='dispotify.artist'),
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dispotify.album'),
        ),
    ]
